### ISSUE TITLE
Dockerfile currently does not build correctly due to missing `isolated-vm` dependency

### ISSUE THREAD

**Issue by Zaperex** [janus-idp/backstage-showcase#369]
### What do you want to improve?

After upgrading to backstage 1.15.0, the required isolated-vim native dependency is not currently installed in the Dockerfile. This results in the built image not running properly.

### What is the current behavior?

When the built image is run in a container, the following error occurs:
```
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module './out/isolated_vm'
Require stack:
- /opt/app-root/src/node_modules/isolated-vm/isolated-vm.js
- /opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-d9bc7a90.cjs.js
- /opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js
- /opt/app-root/src/packages/backend/dist/index.cjs.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/opt/app-root/src/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-d9bc7a90.cjs.js:20:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/app-root/src/node_modules/isolated-vm/isolated-vm.js',
    '/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-d9bc7a90.cjs.js',
    '/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js',
    '/opt/app-root/src/packages/backend/dist/index.cjs.js'
  ]
}

Node.js v18.14.2
```

### What is the new behavior?

The built image will run properly.

### :warning: Is this a breaking change?

_Put an `x` in the boxes that apply_

- [ ] Yes
- [ ] No
- [x] Don't know

**Comment by Zaperex** [comment]
It appears the upstream has just updated the documentation regarding Dockerfiles for this issue.
https://github.com/backstage/backstage/pull/18612#discussion_r1257392564

**Comment by schultzp2020** [comment]
Reopening since https://github.com/janus-idp/backstage-showcase/pull/371 hasn't been tested in the downstream.

**Comment by schultzp2020** [comment]
Closing in favor of https://github.com/janus-idp/backstage-showcase/issues/373
