### ISSUE TITLE
running showcase image with default configurations fail after backstage 1.15.0 upgrade

### ISSUE THREAD

**Issue by Zaperex** [janus-idp/backstage-showcase#384]
### What happened?

EDIT: This initial analysis of the issue is no longer accurate. Please refer to the [comment](https://github.com/janus-idp/backstage-showcase/issues/384#issuecomment-1640461853) below.

`app-config.yaml` is no longer being overwritten by `app-config.example.yaml` when you try to launch the showcase image.
Everything is working as intended on `quay.io/janus-idp/backstage-showcase:sha-fa2fa01`, but stopped working after the backstage 1.15.0 upgrade. (`sha-0eb1b3c` was when the upgrade was merged)

The error below should not exist because of this [line](https://github.com/janus-idp/backstage-showcase/blob/main/app-config.example.yaml#L31) if the overwriting works correctly:
```
Backend failed to start up Error: Invalid app bundle schema. If this error is unexpected you need to run `yarn build` in the app. If that doesn't help you should make sure your config schema is correct and rebuild the app bundle again. Caused by the following schema error, Error: Config validation failed, Config must have required property 'baseUrl' { missingProperty=baseUrl } at /sonarqube
    at readConfigs (/opt/app-root/src/node_modules/@backstage/plugin-app-backend/dist/cjs/router-6f51bb7d.cjs.js:66:13)
    at async Object.createRouter (/opt/app-root/src/node_modules/@backstage/plugin-app-backend/dist/cjs/router-6f51bb7d.cjs.js:237:24)
    at async createPlugin$d (/opt/app-root/src/packages/backend/dist/index.cjs.js:37:10)
    at async main (/opt/app-root/src/packages/backend/dist/index.cjs.js:466:124)
```
A workaround to not get this error is to define the `SONARQUBE_URL` env variable at runtime, but this does not fix the root issue.

### What are the steps to reproduce this issue?

1. Build an image after the backstage 1.15.0 upgrade after the dockerfile was fixed with default configurations (unchanged `app-config.yaml`, `app-config.example.yaml` and `app-config.production.yaml`)
2. Run the image with a postgreSQL database and postgreSQL environmental variables declared (i.e. `POSTGRES_HOST`, `POSTGRES_PASSWORD`, `POSTGRES_PORT`, `POSTGRES_USER`)

### Additional information

- Which devices are affected? ie Desktop, Table, Phone
- Which browsers are affected? ie Chrome, Firefox, Safari, Edge
- Which version are you using?

We only support the last 2 major versions.

Attach any related screenshots, if any.

**Comment by Zaperex** [comment]
Quick update on this issue: so it appears this issue stems from how to they validate the config in the config.d.ts file in the sonarqube [backend](https://github.com/backstage/backstage/blob/master/plugins/sonarqube-backend/config.d.ts) and [frontend](https://github.com/backstage/backstage/blob/master/plugins/sonarqube/config.d.ts). It appears that a recent [upstream PR](https://github.com/backstage/backstage/pull/18480) fixed the issue by making the `baseUrl` into an optional field. I updated the dependencies to include this fix and the issue no longer occurs with our default configurations. However, this change is part of the new backstage 1.16.0 package that got released earlier this morning. 

It appears the reason why this error started occuring after the 1.15.0 upgrade is that this [upstream PR](https://github.com/backstage/backstage/pull/18266) that fixed a typo in the `config.d.ts` was included in the 1.15.0 package upgrade. 

Before that PR, the `config.d.ts` tried matching for `sonarQube` instead of `sonarqube` , so the mandatory `baseUrl` field was not enforced since our `app-config.yaml` does not have `sonarQube`. 

After the upgrade, the config.d.ts now finds `sonarqube` in our `app-config.yaml` , and expects the `baseUrl` to be defined since `sonarqube` now exists in our `app-config.yaml` file:
```yaml
# Plugin: SonarQube
sonarqube:
  baseUrl: ${SONARQUBE_URL}
  apiKey: ${SONARQUBE_TOKEN}
 ```
However, since the `app-config.example.yaml` file doesn't override this, it causes the error above to occur.

In a separate branch before we upgraded to 1.15.0 (using backstage 1.14.2), I changed the `app-config.yaml` `sonarqube` section to `sonarQube` and built an image, and the exact issue above occurred so I think it's safe to assume the typo change is what cause the error.
