### ISSUE TITLE
Showcase backend won't start with example config 

### ISSUE THREAD

**Issue by kadel** [janus-idp/backstage-showcase#477]
### Describe the bug

A clear and concise description of what the bug is. (provide screenshots if applicable)

### Expected Behavior
Showcase starting with default (example) config 

### What are the steps to reproduce this bug?

```
▶ cp app-config.example.yaml app-config.local.yaml

▶ yarn run start
yarn run v1.22.19
$ turbo run start --parallel
• Packages in scope: app, backend
• Running start in 2 packages
• Remote caching disabled
app:start: cache bypass, force executing 5b0a51096ca854b0
backend:start: cache bypass, force executing 44b2ea957cd8fc87
app:start: $ backstage-cli package start
backend:start: $ backstage-cli package start
app:start: ⚠️   Some of the following packages may be outdated or have duplicate installations:
app:start:
app:start:           @backstage/plugin-catalog-backend, @backstage/plugin-kubernetes, @backstage/plugin-scaffolder-backend
app:start:
app:start: ⚠️   This can be resolved using the following command:
app:start:
app:start:           yarn backstage-cli versions:check --fix
app:start:
backend:start: Build succeeded
app:start: Loaded config from app-config.yaml, app-config.local.yaml
app:start: <i> [webpack-dev-server] Project is running at:
app:start: <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://[::1]:3000/
app:start: <i> [webpack-dev-server] Content not from webpack is served from '/Users/tkral/Code/backstage-showcase/packages/app/public' directory
app:start: <i> [webpack-dev-server] 404s will fallback to '/index.html'
app:start: <i> [webpack-dev-middleware] wait until bundle finished: /
backend:start: Loaded config from app-config.yaml, app-config.local.yaml
backend:start: 2023-08-29T15:38:10.405Z backstage info Found 4 new secrets in config that will be redacted
backend:start: Backend failed to start up Error: Missing required config value at 'backend.auth.keys[0].secret'
backend:start:     at ConfigReader.getString (/Users/tkral/Code/backstage-showcase/node_modules/@backstage/config/dist/index.cjs.js:240:13)
backend:start:     at /Users/tkral/Code/backstage-showcase/node_modules/@backstage/backend-common/dist/index.cjs.js:4034:31
backend:start:     at Array.map (<anonymous>)
backend:start:     at ServerTokenManager.fromConfig (/Users/tkral/Code/backstage-showcase/node_modules/@backstage/backend-common/dist/index.cjs.js:4034:14)
backend:start:     at makeCreateEnv (webpack-internal:///./src/index.ts:66:100)
backend:start:     at main (webpack-internal:///./src/index.ts:118:23)
app:start: webpack compiled successfully
```
adding 
```yaml
backend:
  auth:
    keys: []
```
to `app-config.local.yaml` fixes the issue with `backend.auth.keys[0].secret'` but there is another one 
```
backend:start: Backend failed to start up TypeError: Invalid type in config for key 'proxy.endpoints' in 'app-config.local.yaml', got array, wanted object
backend:start:     at ConfigReader.getOptionalConfig (/Users/tkral/Code/backstage-showcase/node_modules/@backstage/config/dist/index.cjs.js:143:13)
backend:start:     at ConfigReader.getConfig (/Users/tkral/Code/backstage-showcase/node_modules/@backstage/config/dist/index.cjs.js:128:24)
backend:start:     at ObservableConfigProxy.select (/Users/tkral/Code/backstage-showcase/node_modules/@backstage/backend-app-api/dist/index.cjs.js:115:41)
backend:start:     at ObservableConfigProxy.get (/Users/tkral/Code/backstage-showcase/node_modules/@backstage/backend-app-api/dist/index.cjs.js:130:17)
backend:start:     at readProxyConfig (/Users/tkral/Code/backstage-showcase/node_modules/@backstage/plugin-proxy-backend/dist/index.cjs.js:104:94)
backend:start:     at createRouter (/Users/tkral/Code/backstage-showcase/node_modules/@backstage/plugin-proxy-backend/dist/index.cjs.js:136:23)
backend:start:     at async createPlugin (webpack-internal:///./src/plugins/proxy.ts:9:12)
backend:start:     at async addPlugin (webpack-internal:///./src/index.ts:109:191)
backend:start:     at async main (webpack-internal:///./src/index.ts:122:5)
app:start: webpack compiled successfully
```
This can be fixed with 
```yaml
proxy:
  endpoints: {}
```
but than you get

```
backend:start: 2023-08-29T15:41:26.505Z proxy info [HPM] Proxy rewrite rule created: "^/api/proxy/quay/api/?" ~> "/" type=plugin
backend:start: Backend failed to start up Error: Proxy target must be a string
backend:start:     at buildMiddleware (/Users/tkral/Code/backstage-showcase/node_modules/@backstage/plugin-proxy-backend/dist/index.cjs.js:35:11)
backend:start:     at /Users/tkral/Code/backstage-showcase/node_modules/@backstage/plugin-proxy-backend/dist/index.cjs.js:163:9
backend:start:     at Array.forEach (<anonymous>)
backend:start:     at configureMiddlewares (/Users/tkral/Code/backstage-showcase/node_modules/@backstage/plugin-proxy-backend/dist/index.cjs.js:159:31)
backend:start:     at createRouter (/Users/tkral/Code/backstage-showcase/node_modules/@backstage/plugin-proxy-backend/dist/index.cjs.js:137:3)
backend:start:     at async createPlugin (webpack-internal:///./src/plugins/proxy.ts:9:12)
backend:start:     at async addPlugin (webpack-internal:///./src/index.ts:109:191)
backend:start:     at async main (webpack-internal:///./src/index.ts:122:5)
```
This one is not easily fixable in `local` config, the only way I found is to remove `proxy.endpoints` from `app-config.yaml`

### Versions of software used and environment
tested on 7fa8b00d3dc7eb4988307877cef8e9ea1fb32145

**Comment by kadel** [comment]
#481 fixes this issue only partialy; there is still a problem with `proxy.endpoints`
