### ISSUE TITLE
ERR_REQUIRE_ESM: require() of ES Module backstage-showcase/node_modules/strip-ansi/index.js from backstage-showcase/node_modules/tty-table/src/style.js not supported.

### ISSUE THREAD

**Issue by nickboldt** [janus-idp/backstage-showcase#728]
Within the last week or so, one or more dependency was updated in package.json/yarn.lock which is now causing GH actions and downstream builds to fail:

```
ERR_REQUIRE_ESM: require() of ES Module backstage-showcase/node_modules/strip-ansi/index.js from backstage-showcase/node_modules/tty-table/src/style.js not supported.
```

https://github.com/janus-idp/backstage-showcase/actions/runs/6710306968/job/18235185205
https://github.com/janus-idp/backstage-showcase/commit/a55e6580b1367a3b0c13387452c6e6a2bbbc51fe

```
[5/5] Building fresh packages...
$ husky install
husky - Git hooks installed
Done in 29.28s.
/usr/bin/git reset --hard a[55](https://github.com/janus-idp/backstage-showcase/actions/runs/6710306968/job/18235185205#step:5:56)e6[58](https://github.com/janus-idp/backstage-showcase/actions/runs/6710306968/job/18235185205#step:5:59)0b1367a3b0c13387452c6e6a2bbbc51fe
HEAD is now at a55e658 fix(backstage): revert #672 (#685)
/opt/hostedtoolcache/node/18.18.2/x64/bin/node /home/runner/work/backstage-showcase/backstage-showcase/node_modules/@changesets/cli/bin.js version
/home/runner/work/backstage-showcase/backstage-showcase/node_modules/tty-table/src/style.js:7
const stripAnsi = require("strip-ansi")
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/backstage-showcase/backstage-showcase/node_modules/strip-ansi/index.js from /home/runner/work/backstage-showcase/backstage-showcase/node_modules/tty-table/src/style.js not supported.
Instead change the require of index.js in /home/runner/work/backstage-showcase/backstage-showcase/node_modules/tty-table/src/style.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/tty-table/src/style.js:7:19)
    at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/tty-table/src/render.js:1:15)
    at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/tty-table/src/factory.js:2:16)
    at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/tty-table/adapters/default-adapter.js:1:17)
    at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/tty-table/src/main.js:7:20)
    at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/@changesets/cli/dist/cli.cjs.dev.js:32:13)
    at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/@changesets/cli/dist/cli.cjs.js:6:20)
    at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/@changesets/cli/bin.js:4:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.18.2
Error: Error: The process '/opt/hostedtoolcache/node/18.18.2/x[64](https://github.com/janus-idp/backstage-showcase/actions/runs/6710306968/job/18235185205#step:5:65)/bin/node' failed with exit code 1
Error: The process '/opt/hostedtoolcache/node/18.18.2/x64/bin/node' failed with exit code 1
```

Similar failure is downstream too:

https://issues.redhat.com/browse/RHIDP-429

**Comment by nickboldt** [comment]
Found an earlier failure:

```
backstage-plugin-catalog-backend-module-github-org:test
  cache miss, executing ec3a3f70d0faece7
  $ backstage-cli package test --coverage
  Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/backstage-showcase/backstage-showcase/node_modules/string-width/index.js from /home/runner/work/backstage-showcase/backstage-showcase/node_modules/cliui/build/index.cjs not supported.
  Instead change the require of index.js in /home/runner/work/backstage-showcase/backstage-showcase/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
      at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/cliui/build/index.cjs:291:21)
      at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/yargs/build/index.cjs:1:60678)
      at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/yargs/index.cjs:5:30)
      at _yargs (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/jest-cli/build/run.js:30:39)
      at buildArgv (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/jest-cli/build/run.js:149:26)
      at Object.run (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/jest-cli/build/run.js:124:24)
      at test (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/@backstage/cli/dist/cjs/test-87ae3d0d.cjs.js:[55](https://github.com/janus-idp/backstage-showcase/actions/runs/6709556643/job/18232865570#step:8:64):25)
      at Command.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/@backstage/cli/dist/cjs/index-148826cb.cjs.js:477:13)
  error Command failed with exit code 1.
  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  Error:  command finished with error: command (/home/runner/work/backstage-showcase/backstage-showcase/dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-github-org-dynamic) yarn run test exited (1)
```

https://github.com/janus-idp/backstage-showcase/pull/684
https://github.com/janus-idp/backstage-showcase/actions/runs/6709556643/job/18232865570

**Comment by nickboldt** [comment]
First PR https://github.com/janus-idp/backstage-showcase/pull/729
