### ISSUE TITLE
Typo in backend dynamic plugins

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-showcase#813]
### Describe the bug

Some packages fail to start:

```
======= Installing dynamic plugin ./dynamic-plugins/dist/janus-idp-backstage-scaffolder-backend-module-quay
==> Grabbing package archive through `npm pack`
Traceback (most recent call last):
File "/opt/app-root/src/install-dynamic-plugins.py", line 304, in <module>
main()
File "/opt/app-root/src/install-dynamic-plugins.py", line 230, in main
raise InstallException(f'Error while installing plugin { package } with \'npm pack\' : ' + completed.stderr.decode('utf-8'))
__main__.InstallException: Error while installing plugin /opt/app-root/src/dynamic-plugins/dist/janus-idp-backstage-scaffolder-backend-module-quay with 'npm pack' : npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /opt/app-root/src/dynamic-plugins/dist/janus-idp-backstage-scaffolder-backend-module-quay/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/opt/app-root/src/dynamic-plugins/dist/janus-idp-backstage-scaffolder-backend-module-quay/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

Seems like we have a typo in few package names (missing `-dynamic` suffix)

**Comment by tumido** [comment]
Closed via https://github.com/janus-idp/backstage-showcase/pull/814
