### ISSUE TITLE
GH action `release`  is failing

### ISSUE THREAD

**Issue by nickboldt** [janus-idp/backstage-showcase#841]
### Describe the bug

GH release action has been failing for a couple months now...

```
[5/5] Building fresh packages...
$ husky install
husky - Git hooks installed
Done in 57.[55](https://github.com/janus-idp/backstage-showcase/actions/runs/7212586680/job/19650579904#step:5:56)s.
/usr/bin/git reset --hard 8a59b96a9bb11552916df72f5a9e932bce7bdbee
HEAD is now at 8a[59](https://github.com/janus-idp/backstage-showcase/actions/runs/7212586680/job/19650579904#step:5:60)b96 chore(deps): bump @adobe/css-tools from 4.3.1 to 4.3.2 (#826)
/opt/hostedtoolcache/node/18.18.2/x64/bin/node /home/runner/work/backstage-showcase/backstage-showcase/node_modules/@changesets/cli/bin.js version
/home/runner/work/backstage-showcase/backstage-showcase/node_modules/tty-table/src/style.js:7
const stripAnsi = require("strip-ansi")
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/backstage-showcase/backstage-showcase/node_modules/strip-ansi/index.js from /home/runner/work/backstage-showcase/backstage-showcase/node_modules/tty-table/src/style.js not supported.
Instead change the require of index.js in /home/runner/work/backstage-showcase/backstage-showcase/node_modules/tty-table/src/style.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/tty-table/src/style.js:7:19)
    at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/tty-table/src/render.js:1:15)
    at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/tty-table/src/factory.js:2:16)
    at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/tty-table/adapters/default-adapter.js:1:17)
    at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/tty-table/src/main.js:7:20)
    at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/@changesets/cli/dist/cli.cjs.dev.js:32:13)
    at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/@changesets/cli/dist/cli.cjs.js:6:20)
    at Object.<anonymous> (/home/runner/work/backstage-showcase/backstage-showcase/node_modules/@changesets/cli/bin.js:4:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.18.2
Error: Error: The process '/opt/hostedtoolcache/node/18.18.2/x[64](https://github.com/janus-idp/backstage-showcase/actions/runs/7212586680/job/19650579904#step:5:65)/bin/node' failed with exit code 1
Error: The process '/opt/hostedtoolcache/node/18.18.2/x64/bin/node' failed with exit code 1
```
-- https://github.com/janus-idp/backstage-showcase/actions/runs/7212586680/job/19650579904
-- https://github.com/janus-idp/backstage-showcase/actions/workflows/release.yaml

Last time this passed was https://github.com/janus-idp/backstage-showcase/actions/runs/6709561009 on Oct 31. 
### What are the steps to reproduce this bug?

1. push a commit
2. watch it fail at https://github.com/janus-idp/backstage-showcase/actions/workflows/release.yaml

**Comment by nickboldt** [comment]
Release action removed as we no longer need it -- see https://github.com/janus-idp/backstage-showcase/pull/891
